import {
  Column,
  CreateDateColumn,
  Entity,
  Index,
  JoinColumn,
  ManyToOne,
  PrimaryColumn,
} from 'typeorm';
import { User } from '../../users/user.entity';

/**
 * One row per issued refresh token. The raw token is never stored — only its
 * SHA-256 digest. Rows are revoked (not deleted) on rotation and logout so
 * replay of an old token can be detected.
 */
@Entity({ name: 'refresh_sessions' })
export class RefreshSession {
  /** Generated by the app: it is embedded in the token (`sid`) before insert. */
  @PrimaryColumn('uuid', { primaryKeyConstraintName: 'PK_refresh_sessions' })
  id: string;

  @Index('IDX_refresh_sessions_user_id')
  @Column({ name: 'user_id', type: 'uuid' })
  userId: string;

  @ManyToOne(() => User, { onDelete: 'CASCADE' })
  @JoinColumn({
    name: 'user_id',
    foreignKeyConstraintName: 'FK_refresh_sessions_user_id',
  })
  user?: User;

  /** Hex SHA-256 of the refresh token. */
  @Column({ name: 'token_hash', type: 'char', length: 64 })
  tokenHash: string;

  @Column({ name: 'expires_at', type: 'timestamptz' })
  expiresAt: Date;

  @CreateDateColumn({ name: 'created_at', type: 'timestamptz' })
  createdAt: Date;

  @Column({ name: 'revoked_at', type: 'timestamptz', nullable: true })
  revokedAt: Date | null;
}
